FROM python:3.12-slim
WORKDIR /app
COPY pyproject.toml /app/
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
CMD ["gunicorn", "apps.api.wsgi:application", "-b", "0.0.0.0:8000"]
