apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-rest-api
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: django-rest-api
          env:
            - name: APP_ENV
              value: production
